site_name: RLD+ Entity Documentation
site_url: https://averagefree2play.github.io/rldplus_entity_docs/
nav:
  - Introduction: index.md
  - Features: features.md
  - API Reference:
      - Entity: api_entity.md
      - EntityData: api_entity_data.md
      - Chaser: api_chaser.md
      - ChaserData: api_chaser_data.md
      - Checker: api_checker.md
      - CheckerData: api_checker_data.md
      - Summoner: api_summoner.md
      - SummonerData: api_summoner_data.md
theme:
  name: material
  favicon: images/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AverageFree2Play/RLDPlus-Docs
      name: GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/GxcZ6Tx2Hm
      name: Discord
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      permalink: true
repo_url: https://github.com/AverageFree2Play/RLDPlus-Docs
repo_name: AverageFree2Play/RLDPlus-Docs